### ISSUE TITLE
SJCOG Project completion checklist

### ISSUE THREAD

**Issue by lindsaypoirier** [Hack-for-California/Gentrification-in-the-Central-Valley#2]
- [ ] View UDP code, fork, and run (README file)
[code link](https://github.com/urban-displacement/displacement-typologies)

- [ ] Make plan for replication - replicate 13-county model for San Joaquin only

- [ ] Meet with Sara and Asiya (maybe Bernadette) to present plan Dec. 4, 11:00-11:45 AM

- [ ] Execute plan
